name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: install
        run: npm install
      - name: test-cjs
        run: node --test src/getUserAgent.spec.cjs
      - name: test-mjs
        run: node --test src/getUserAgent.spec.cjs

  test-typescript:
    runs-on: ubuntu-latest
    env:
      TSC_VERSION: "5.9.3"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: install
        run: |
          npm install
          npm install -D -E typescript@$TSC_VERSION
      - name: test-cjs
        run: node --test src/getUserAgent.spec.cjs
      - name: test-mjs
        run: node --test src/getUserAgent.spec.mjs

  test-typescript-detection-disabled:
    runs-on: ubuntu-latest
    env:
      TSC_VERSION: "5.9.3"
      AWS_SDK_JS_TYPESCRIPT_DETECTION_DISABLED: "true"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: install
        run: |
          npm install
          npm install -D -E typescript@$TSC_VERSION
      - name: test-cjs
        run: node --test src/getUserAgent.spec.cjs
      - name: test-mjs
        run: node --test src/getUserAgent.spec.mjs

  test-typescript-missing-dev-deps-in-package-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: install
        run: |
          npm install
          npm install -D -E typescript@5.9.3
          jq 'del(.devDependencies.typescript)' package.json > tmp.json && mv tmp.json package.json
      - name: test-cjs
        run: node --test src/getUserAgent.spec.cjs
      - name: test-mjs
        run: node --test src/getUserAgent.spec.mjs
